#!/usr/bin/env node
/**
 * Manual duplicate-identity review server.
 *
 *   npm run review          then open http://localhost:5175
 *
 * A local-only authoring tool, same category as the indexer itself: it reads
 * face-index/review.json (generated by `npm run index-faces`) and lets you
 * decide, pair by pair, whether two guest ids are the same person. Decisions
 * are recorded to face-index/review-decisions.json immediately — nothing
 * about the face index itself changes until you explicitly click "Apply".
 *
 * Applying re-runs the REAL pipeline (spawns the same `--from=cluster` command
 * `npm run index-faces:recluster` runs) so every existing mechanism — the
 * ledger, identity consolidation, derivatives, emit — does the actual work.
 * This server only ever edits face-index/overrides.json and then hands off;
 * it never re-implements clustering.
 */

import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const UI_DIR = path.join(ROOT, 'tools', 'review-ui');
const GALLERY_DIR = path.join(ROOT, 'assets', 'gallery');
const REVIEW_JSON = path.join(ROOT, 'face-index', 'review.json');
const OVERRIDES_JSON = path.join(ROOT, 'face-index', 'overrides.json');
const DECISIONS_JSON = path.join(ROOT, 'face-index', 'review-decisions.json');
const LEDGER_JSON = path.join(ROOT, 'face-index', '.people-ledger.json');
const DATA_DIR = path.join(ROOT, 'data');
const BACKUPS_DIR = path.join(ROOT, 'face-index', 'backups');

const PORT = Number(process.env.PORT || 5175);

// ---------------------------------------------------------------- utilities

async function readJson(file, fallback) {
  try {
    return JSON.parse(await fs.readFile(file, 'utf8'));
  } catch (err) {
    if (err.code === 'ENOENT') return fallback;
    throw err;
  }
}

/** Write-to-temp-then-rename so a crash mid-write can never corrupt the file. */
async function writeJsonAtomic(file, obj) {
  const tmp = `${file}.tmp-${process.pid}-${Date.now()}`;
  await fs.writeFile(tmp, `${JSON.stringify(obj, null, 2)}\n`, 'utf8');
  await fs.rename(tmp, file);
}

function pairKey(a, b) {
  return [a, b].sort().join('|');
}

async function loadDecisions() {
  const doc = await readJson(DECISIONS_JSON, { version: 1, decisions: {} });
  if (!doc.decisions) doc.decisions = {};
  return doc;
}

async function loadOverrides() {
  const raw = await readJson(OVERRIDES_JSON, {});
  return {
    version: 1, people: {}, merge: [], split: {}, ignoreFaces: [], ignorePhotos: [], doNotMerge: [],
    ...raw,
  };
}

function send(res, status, body, headers = {}) {
  res.writeHead(status, { 'content-type': 'application/json', ...headers });
  res.end(JSON.stringify(body));
}

async function readBody(req) {
  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  const raw = Buffer.concat(chunks).toString('utf8');
  return raw ? JSON.parse(raw) : {};
}

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json',
  '.webp': 'image/webp',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.svg': 'image/svg+xml',
};

/** Serves a file from `baseDir`, refusing to escape it (no `..` traversal). */
async function serveStatic(res, baseDir, relPath) {
  const full = path.normalize(path.join(baseDir, relPath));
  if (!full.startsWith(path.normalize(baseDir))) { send(res, 403, { error: 'forbidden' }); return; }
  try {
    const data = await fs.readFile(full);
    const ext = path.extname(full).toLowerCase();
    res.writeHead(200, { 'content-type': MIME[ext] ?? 'application/octet-stream', 'cache-control': 'no-cache' });
    res.end(data);
  } catch {
    send(res, 404, { error: 'not found' });
  }
}

// -------------------------------------------------------------- /api/data

/** The SAME final (a, b) person-pair can appear more than once in
 *  possibleDuplicateIdentities: tier 2 can block several DIFFERENT
 *  intermediate node-pairs against Sharon (say), and some of THOSE fragments
 *  can later fold into a different surviving id via the ledger — at which
 *  point what were genuinely distinct tier-2 decisions all resolve to the
 *  same final (a, b) once identify.mjs maps representative faces to person
 *  ids. Without deduplicating, the review UI would ask about the same two
 *  guests more than once and inflate every count. Keep the smallest
 *  (most-confident) distance as the representative row. */
function dedupePairs(pairs) {
  const byKey = new Map();
  for (const p of pairs) {
    const key = pairKey(p.a, p.b);
    const existing = byKey.get(key);
    if (!existing || p.distance < existing.distance) byKey.set(key, p);
  }
  return [...byKey.values()].sort((x, y) => x.distance - y.distance);
}

async function handleData(res) {
  const review = await readJson(REVIEW_JSON, null);
  if (!review) {
    send(res, 200, { ready: false, message: 'face-index/review.json not found — run npm run index-faces first.' });
    return;
  }
  const decisionsDoc = await loadDecisions();
  const people = {};
  for (const p of review.people ?? []) people[p.id] = p;
  send(res, 200, {
    ready: true,
    generatedAt: review.generatedAt,
    stats: review.stats,
    pairs: dedupePairs(review.possibleDuplicateIdentities ?? []),
    people,
    decisions: decisionsDoc.decisions,
  });
}

// ---------------------------------------------------------- /api/decision

async function handleDecision(req, res) {
  const body = await readBody(req);
  const { a, b, decision } = body;
  if (!a || !b || !['same', 'different', 'skip', 'unset'].includes(decision)) {
    send(res, 400, { error: 'expected { a, b, decision: same|different|skip|unset }' });
    return;
  }
  const doc = await loadDecisions();
  const key = pairKey(a, b);
  if (decision === 'unset') {
    delete doc.decisions[key];
  } else {
    doc.decisions[key] = {
      a, b,
      nameA: body.nameA ?? null,
      nameB: body.nameB ?? null,
      decision,
      decidedAt: new Date().toISOString(),
    };
  }
  await writeJsonAtomic(DECISIONS_JSON, doc);
  send(res, 200, { ok: true, decisions: doc.decisions });
}

// ----------------------------------------------------------- /api/apply

/** Union-find over both the EXISTING merge groups and the newly-confirmed
 *  "same person" pairs, so a chain of decisions (A=B, B=C) collapses into one
 *  group, and a decision touching an already-merged identity extends that
 *  group instead of fighting it for a canonical id. */
function computeMergeGroups(existingGroups, samePairs, photoCountOf) {
  const parent = new Map();
  const find = (x) => {
    if (!parent.has(x)) parent.set(x, x);
    let r = x;
    while (parent.get(r) !== r) r = parent.get(r);
    let cur = x;
    while (parent.get(cur) !== r) { const next = parent.get(cur); parent.set(cur, r); cur = next; }
    return r;
  };
  const union = (x, y) => { const rx = find(x); const ry = find(y); if (rx !== ry) parent.set(rx, ry); };

  const existingCanonical = new Set(existingGroups.map((g) => g[0]));
  for (const group of existingGroups) {
    const [canon, ...rest] = group;
    find(canon);
    for (const id of rest) union(canon, id);
  }
  for (const [a, b] of samePairs) union(a, b);

  const membersByRoot = new Map();
  for (const id of parent.keys()) {
    const r = find(id);
    if (!membersByRoot.has(r)) membersByRoot.set(r, new Set());
    membersByRoot.get(r).add(id);
  }

  const groups = [];
  for (const members of membersByRoot.values()) {
    if (members.size < 2) continue;
    const list = [...members];
    let canonical = list.find((id) => existingCanonical.has(id));
    if (!canonical) {
      canonical = list.reduce((best, id) => ((photoCountOf(id) ?? 0) > (photoCountOf(best) ?? 0) ? id : best), list[0]);
    }
    groups.push([canonical, ...list.filter((id) => id !== canonical)]);
  }
  return groups;
}

function mergeDoNotMergeLists(existing, newPairs) {
  const seen = new Set(existing.map(([a, b]) => pairKey(a, b)));
  const out = existing.map((p) => [...p]);
  for (const [a, b] of newPairs) {
    const k = pairKey(a, b);
    if (seen.has(k)) continue;
    seen.add(k);
    out.push([a, b]);
  }
  return out;
}

async function backupCurrentState() {
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const dir = path.join(BACKUPS_DIR, stamp);
  await fs.mkdir(dir, { recursive: true });
  const targets = [
    [OVERRIDES_JSON, 'overrides.json'],
    [LEDGER_JSON, '.people-ledger.json'],
    [REVIEW_JSON, 'review.json'],
    [path.join(DATA_DIR, 'photos.json'), 'data-photos.json'],
    [path.join(DATA_DIR, 'people.json'), 'data-people.json'],
    [path.join(DATA_DIR, 'photo-faces.json'), 'data-photo-faces.json'],
  ];
  for (const [src, name] of targets) {
    try { await fs.copyFile(src, path.join(dir, name)); } catch { /* missing file: nothing to back up yet */ }
  }
  return dir;
}

function runRecluster() {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, [path.join(ROOT, 'tools', 'face-index', 'cli.mjs'), '--from=cluster'], {
      cwd: ROOT,
    });
    let out = '';
    child.stdout.on('data', (d) => { out += d; });
    child.stderr.on('data', (d) => { out += d; });
    child.on('close', (code) => resolve({ code, output: out }));
  });
}

async function handleApply(req, res) {
  const decisionsDoc = await loadDecisions();
  const entries = Object.values(decisionsDoc.decisions);
  const samePairs = entries.filter((e) => e.decision === 'same').map((e) => [e.a, e.b]);
  const differentPairs = entries.filter((e) => e.decision === 'different').map((e) => [e.a, e.b]);
  const skippedCount = entries.filter((e) => e.decision === 'skip').length;

  if (!samePairs.length && !differentPairs.length) {
    send(res, 400, { error: 'No "same" or "different" decisions to apply yet.' });
    return;
  }

  const beforeReview = await readJson(REVIEW_JSON, null);
  const beforePeople = await readJson(path.join(DATA_DIR, 'people.json'), { people: [] });
  const beforeById = new Map(beforePeople.people.map((p) => [p.id, p]));
  const photoCountOf = (id) => beforeById.get(id)?.photoCount ?? 0;

  const backupDir = await backupCurrentState();

  const overrides = await loadOverrides();
  const newMergeGroups = computeMergeGroups(overrides.merge ?? [], samePairs, photoCountOf);
  // Groups untouched by this batch (no member is a canonical or participant
  // above) must be preserved too — computeMergeGroups only returns groups
  // that had >=2 members reachable from EITHER an existing group OR a new
  // pair, which is already every existing group (each seeds its own union),
  // so nothing is lost; this line is just the replacement, not an append.
  overrides.merge = newMergeGroups;
  overrides.doNotMerge = mergeDoNotMergeLists(overrides.doNotMerge ?? [], differentPairs);
  overrides._reviewToolNote = [
    `Last applied from the manual review UI at ${new Date().toISOString()}:`,
    `${samePairs.length} pair(s) marked same-person, ${differentPairs.length} marked different-people.`,
    `Backup of the pre-apply state: face-index/backups/${path.basename(backupDir)}/`,
  ];
  await writeJsonAtomic(OVERRIDES_JSON, overrides);

  const { code, output } = await runRecluster();
  if (code !== 0) {
    send(res, 500, {
      error: 'Re-clustering failed. overrides.json was updated but the pipeline did not complete successfully.',
      backupDir, output: output.slice(-4000),
    });
    return;
  }

  const afterReview = await readJson(REVIEW_JSON, null);
  const afterPeople = await readJson(path.join(DATA_DIR, 'people.json'), { people: [] });
  const afterById = new Map(afterPeople.people.map((p) => [p.id, p]));
  const ledger = await readJson(LEDGER_JSON, { aliases: {} });
  const resolveAlias = (id) => {
    let cur = id; const seen = new Set();
    while (ledger.aliases?.[cur] && !seen.has(cur)) { seen.add(cur); cur = ledger.aliases[cur]; }
    return cur;
  };

  // ---- validation -----------------------------------------------------
  const conflicts = [];

  if (beforeReview && afterReview && beforeReview.stats.facesDetected !== afterReview.stats.facesDetected) {
    conflicts.push(`Face count changed unexpectedly: ${beforeReview.stats.facesDetected} -> ${afterReview.stats.facesDetected}.`);
  }
  if (beforeReview && afterReview && beforeReview.stats.photosScanned !== afterReview.stats.photosScanned) {
    conflicts.push(`Photo count changed unexpectedly: ${beforeReview.stats.photosScanned} -> ${afterReview.stats.photosScanned}.`);
  }

  // No existing person's photo list may ever shrink — whether or not this
  // batch touched them.
  for (const before of beforePeople.people) {
    const after = afterById.get(before.id);
    if (!after) continue; // merged away or hidden this batch — checked below instead
    const afterSet = new Set(after.photos);
    const lost = before.photos.filter((id) => !afterSet.has(id));
    if (lost.length) conflicts.push(`${before.id} lost ${lost.length} photo(s) it had before: ${lost.slice(0, 5).join(', ')}`);
  }

  let photosReassigned = 0;
  for (const [a, b] of samePairs) {
    const ra = resolveAlias(a);
    const rb = resolveAlias(b);
    if (ra !== rb) {
      conflicts.push(`Confirmed same-person pair ${a} / ${b} did NOT end up consolidated (resolved to ${ra} and ${rb}).`);
      continue;
    }
    const survivor = afterById.get(ra);
    const beforeA = beforeById.get(a);
    const beforeB = beforeById.get(b);
    const beforeUnion = new Set([...(beforeA?.photos ?? []), ...(beforeB?.photos ?? [])]);
    if (survivor) {
      const survivorSet = new Set(survivor.photos);
      const missing = [...beforeUnion].filter((id) => !survivorSet.has(id));
      if (missing.length) conflicts.push(`${a} + ${b} merged into ${ra}, but ${missing.length} photo(s) are missing from the result.`);
    }
    photosReassigned += Math.min(beforeA?.photoCount ?? 0, beforeB?.photoCount ?? 0);
  }

  for (const [a, b] of differentPairs) {
    const ra = resolveAlias(a);
    const rb = resolveAlias(b);
    if (ra === rb) conflicts.push(`Confirmed different-people pair ${a} / ${b} ended up merged (both resolve to ${ra}).`);
  }

  const now = new Date().toISOString();
  for (const e of entries) {
    if (e.decision === 'same' || e.decision === 'different') e.appliedAt = now;
  }
  await writeJsonAtomic(DECISIONS_JSON, decisionsDoc);

  send(res, 200, {
    ok: true,
    backupDir: path.relative(ROOT, backupDir),
    before: { people: beforePeople.people.length },
    after: { people: afterPeople.people.length },
    mergesApplied: samePairs.length,
    confirmedSeparate: differentPairs.length,
    skipped: skippedCount,
    photosReassigned,
    conflicts,
    pipelineOutput: output.slice(-4000),
  });
}

// --------------------------------------------------------------- server

const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url, 'http://localhost');
    const p = url.pathname;

    if (req.method === 'GET' && p === '/api/data') return void (await handleData(res));
    if (req.method === 'POST' && p === '/api/decision') return void (await handleDecision(req, res));
    if (req.method === 'POST' && p === '/api/apply') return void (await handleApply(req, res));

    if (p.startsWith('/gallery/')) return void (await serveStatic(res, GALLERY_DIR, p.slice('/gallery/'.length)));

    if (p === '/' || p === '') return void (await serveStatic(res, UI_DIR, 'index.html'));
    return void (await serveStatic(res, UI_DIR, p.slice(1)));
  } catch (err) {
    send(res, 500, { error: String(err?.stack ?? err) });
  }
});

server.listen(PORT, () => {
  console.log(`\n  Duplicate-identity review  →  http://localhost:${PORT}\n`);
});
